### ISSUE TITLE
Add options for positioning and max size

### ISSUE THREAD

**Issue by alexdreptu** [TheNatriX/lognotify#1]
When I open lognotify on i3wm, it covers my dzen2 top bar and as the number of log lines to display grows so does the lognotify pop-up which in turn covers half of my browser window and sometimes my whole display. It would be nice to have some options to specify its position on the screen and its max size, like [dzen](https://github.com/robm/dzen) has or [rofi](https://davedavenport.github.io/rofi/).

**Comment by YO3BN** [comment]
Hello,
I'm working already to the new X client implementation which will solve the all mentioned issues and many others regarding the notification window.
The new X implementation is in a separate branch named: xw_resize

Stay tuned !
